import { Product } from './types'

export const products: Product[] = [
  {
    id: 'prod-001',
    name: 'Gentle Charcoal Cleanser',
    description: 'A luxurious deep-cleansing formula infused with activated charcoal and green tea extract to purify pores while maintaining skin\'s natural moisture balance.',
    price: 450,
    category: 'cleanser',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500&h=500&fit=crop',
    ingredients: ['Activated Charcoal', 'Green Tea Extract', 'Aloe Vera', 'Glycerin', 'Vitamin E'],
    benefits: ['Deep cleanses pores', 'Removes impurities', 'Balances oil production', 'Gentle on sensitive skin'],
    usage: 'Apply to damp face, massage gently in circular motions, and rinse thoroughly. Use morning and evening.',
    inStock: true,
    isNew: true
  },
  {
    id: 'prod-002',
    name: 'Vitamin C Brightening Cream',
    description: 'A potent antioxidant cream with 15% vitamin C, hyaluronic acid, and ferulic acid to brighten skin tone and reduce signs of aging.',
    price: 850,
    category: 'cream',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500&h=500&fit=crop',
    ingredients: ['Vitamin C 15%', 'Hyaluronic Acid', 'Ferulic Acid', 'Vitamin E', 'Rose Water'],
    benefits: ['Brightens complexion', 'Reduces dark spots', 'Boosts collagen', 'Evens skin tone'],
    usage: 'Apply to clean face and neck. Gently massage until absorbed. Use in the morning before moisturizer.',
    inStock: true,
    isNew: true
  },
  {
    id: 'prod-003',
    name: 'Niacinamide Pore Refining Cream',
    description: 'A lightweight cream with 10% niacinamide and zinc to minimize pores, control sebum, and improve skin texture.',
    price: 650,
    category: 'cream',
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=500&h=500&fit=crop',
    ingredients: ['Niacinamide 10%', 'Zinc PCA', 'Witch Hazel', 'Chamomile Extract', 'Allantoin'],
    benefits: ['Minimizes pores', 'Controls oil', 'Reduces blemishes', 'Improves texture'],
    usage: 'Apply to face after cleansing. Use morning and evening before moisturizer.',
    inStock: true
  },
  {
    id: 'prod-004',
    name: 'Hydrating Rose Toner',
    description: 'An alcohol-free toner enriched with rose water, hyaluronic acid, and aloe vera to hydrate and balance skin pH.',
    price: 380,
    category: 'toner',
    image: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=500&h=500&fit=crop',
    ingredients: ['Rose Water', 'Hyaluronic Acid', 'Aloe Vera', 'Cucumber Extract', 'Glycerin'],
    benefits: ['Balances pH', 'Hydrates skin', 'Soothes irritation', 'Preps for serums'],
    usage: 'After cleansing, apply to face using a cotton pad or pat in with hands. Follow with serum.',
    inStock: true
  },
  {
    id: 'prod-005',
    name: 'Retinol Night Renewal Cream',
    description: 'A powerful anti-aging cream with encapsulated retinol and bakuchiol to reduce fine lines and renew skin overnight.',
    price: 950,
    category: 'cream',
    image: 'https://images.unsplash.com/photo-1611930021592-a8cfd5319ceb?w=500&h=500&fit=crop',
    ingredients: ['Retinol 0.5%', 'Bakuchiol', 'Squalane', 'Peptides', 'Vitamin E'],
    benefits: ['Reduces fine lines', 'Improves firmness', 'Renews skin cells', 'Smooths texture'],
    usage: 'Apply to clean face at night only. Start with twice weekly, gradually increase frequency.',
    inStock: false
  },
  {
    id: 'prod-006',
    name: 'Hyaluronic Acid Moisturizer',
    description: 'An ultra-hydrating moisturizer with three molecular weights of hyaluronic acid to deeply hydrate and plump skin.',
    price: 550,
    category: 'moisturizer',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500&h=500&fit=crop',
    ingredients: ['Hyaluronic Acid Complex', 'Ceramides', 'Squalane', 'Niacinamide', 'Shea Butter'],
    benefits: ['Deep hydration', 'Plumps skin', 'Strengthens barrier', 'Suitable for all skin types'],
    usage: 'Apply to face and neck after serum. Use morning and evening. Can be layered under SPF.',
    inStock: true
  },
  {
    id: 'prod-007',
    name: 'Clay Detox Mask',
    description: 'A purifying mask with kaolin and bentonite clay, activated charcoal, and tea tree oil to deeply cleanse and detoxify.',
    price: 480,
    category: 'mask',
    image: 'https://images.unsplash.com/photo-1570554886111-e80fcca6a029?w=500&h=500&fit=crop',
    ingredients: ['Kaolin Clay', 'Bentonite Clay', 'Activated Charcoal', 'Tea Tree Oil', 'Aloe Vera'],
    benefits: ['Detoxifies pores', 'Absorbs excess oil', 'Clarifies skin', 'Prevents breakouts'],
    usage: 'Apply thin layer to clean, damp face. Leave for 10-15 minutes. Rinse with warm water. Use 2-3 times weekly.',
    inStock: true
  },
  {
    id: 'prod-008',
    name: 'Overnight Sleeping Mask',
    description: 'A rich overnight mask with hyaluronic acid, peptides, and botanical oils to deeply nourish and repair skin while you sleep.',
    price: 720,
    category: 'mask',
    image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=500&h=500&fit=crop',
    ingredients: ['Hyaluronic Acid', 'Peptide Complex', 'Rosehip Oil', 'Lavender Extract', 'Vitamin B5'],
    benefits: ['Intensive hydration', 'Repairs overnight', 'Plumps fine lines', 'Soothes skin'],
    usage: 'Apply as the last step of evening routine. Leave on overnight, rinse in morning if desired.',
    inStock: true
  },
  {
    id: 'prod-009',
    name: 'Oil-Control Mattifying Moisturizer',
    description: 'A lightweight gel-cream moisturizer with niacinamide and salicylic acid to control shine and minimize pores.',
    price: 490,
    category: 'moisturizer',
    image: 'https://images.unsplash.com/photo-1617897903246-719242758050?w=500&h=500&fit=crop',
    ingredients: ['Niacinamide', 'Salicylic Acid', 'Zinc PCA', 'Green Tea Extract', 'Hyaluronic Acid'],
    benefits: ['Controls oil', 'Mattifies skin', 'Minimizes pores', 'Lightweight hydration'],
    usage: 'Apply to clean face after serum. Perfect for oily and combination skin. Use daily.',
    inStock: true
  },
  {
    id: 'prod-010',
    name: 'Exfoliating AHA/BHA Toner',
    description: 'A chemical exfoliating toner with glycolic acid, salicylic acid, and lactic acid to gently resurface and brighten skin.',
    price: 580,
    category: 'toner',
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=500&h=500&fit=crop',
    ingredients: ['Glycolic Acid 5%', 'Salicylic Acid 2%', 'Lactic Acid', 'Witch Hazel', 'Aloe Vera'],
    benefits: ['Exfoliates dead cells', 'Unclogs pores', 'Brightens complexion', 'Smooths texture'],
    usage: 'Apply with cotton pad after cleansing. Use 2-3 times weekly initially. Avoid eye area. Follow with hydration.',
    inStock: false
  },
  {
    id: 'prod-011',
    name: 'Soothing Gel Cleanser',
    description: 'A gentle, pH-balanced gel cleanser with aloe vera, chamomile, and cucumber to cleanse without stripping moisture.',
    price: 420,
    category: 'cleanser',
    image: 'https://images.unsplash.com/photo-1585652757173-57de5e9fab42?w=500&h=500&fit=crop',
    ingredients: ['Aloe Vera', 'Chamomile Extract', 'Cucumber Extract', 'Glycerin', 'Pro-Vitamin B5'],
    benefits: ['Gentle cleansing', 'Calms irritation', 'Maintains pH balance', 'Suitable for sensitive skin'],
    usage: 'Massage onto damp face, rinse with lukewarm water. Use morning and evening for all skin types.',
    inStock: true
  },
  {
    id: 'prod-012',
    name: 'Rich Repair Night Cream',
    description: 'An intensive night cream with ceramides, peptides, and plant oils to repair and strengthen skin barrier overnight.',
    price: 780,
    category: 'moisturizer',
    image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=500&h=500&fit=crop',
    ingredients: ['Ceramide Complex', 'Peptides', 'Shea Butter', 'Jojoba Oil', 'Vitamin E'],
    benefits: ['Repairs skin barrier', 'Deep nourishment', 'Anti-aging', 'Locks in moisture'],
    usage: 'Apply to face and neck as the final step of nighttime routine. Gently massage until absorbed.',
    inStock: true
  },
  {
    id: 'prod-013',
    name: 'Glow-Boosting Sheet Mask',
    description: 'A hydrating sheet mask infused with vitamin C, niacinamide, and botanical extracts for instant radiance.',
    price: 150,
    category: 'mask',
    image: 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=500&h=500&fit=crop',
    ingredients: ['Vitamin C', 'Niacinamide', 'Hyaluronic Acid', 'Licorice Extract', 'Rose Water'],
    benefits: ['Instant radiance', 'Brightens dull skin', 'Deeply hydrates', 'Revitalizes complexion'],
    usage: 'Apply to clean face, leave for 15-20 minutes. Remove and pat remaining essence into skin. Use 2-3 times weekly.',
    inStock: true,
    isNew: true
  },
  {
    id: 'prod-014',
    name: 'Foaming Cream Cleanser',
    description: 'A luxurious cream-to-foam cleanser with coconut-derived surfactants and shea butter for effective yet gentle cleansing.',
    price: 520,
    category: 'cleanser',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500&h=500&fit=crop',
    ingredients: ['Coconut Surfactants', 'Shea Butter', 'Oat Extract', 'Glycerin', 'Vitamin E'],
    benefits: ['Rich lather', 'Deep cleansing', 'Moisturizing', 'Removes makeup'],
    usage: 'Dispense small amount, add water to create foam. Massage onto face and rinse thoroughly.',
    inStock: true
  },
  {
    id: 'prod-015',
    name: 'Antioxidant Recovery Cream',
    description: 'A powerful cream packed with antioxidants including vitamin E, resveratrol, and green tea to protect and repair skin.',
    price: 890,
    category: 'cream',
    image: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=500&h=500&fit=crop',
    ingredients: ['Vitamin E', 'Resveratrol', 'Green Tea Extract', 'Coenzyme Q10', 'Ferulic Acid'],
    benefits: ['Fights free radicals', 'Repairs damage', 'Anti-aging', 'Protects from pollution'],
    usage: 'Apply to clean face morning and evening. Layer under moisturizer and SPF.',
    inStock: false
  }
]
